import Head from "next/head"
import { FC, PropsWithChildren } from "react"
import { MainNav } from "./MainNav"

export const Layout:FC<PropsWithChildren> = ({
   children
}) => {
   return (
      <>
         <Head>
            <title>Laup Wing</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="w-screen h-screen inset-0 flex flex-col overflow-y-auto pb-10 fixed bg-white">
            <MainNav />
            <main className="w-full max-w-4xl mx-auto grid grid-cols-1 gap-6">
               { children }
            </main>
         </div>
      </>
   )
}
